name: bedrock-litellm-proxy

services:
  litellm:
    build: .
    ports:
      - "4000:4000"
    environment:
      # These will be provided by the ECS credential server
      - AWS_CONTAINER_CREDENTIALS_FULL_URI=http://host.docker.internal:9999/ecs/credentials
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
